export const PRODUCT_CATEGORIES_REPOSITORY = Symbol('PRODUCT_CATEGORY_REPOSITORY')
export const PRODUCT_CATEGORIES_TRANSLATIONS_REPOSITORY = Symbol(
	'PRODUCT_CATEGORIES_TRANSLATIONS_REPOSITORY',
)

export const PRODUCT_CATEGORIES_SERVICE = Symbol('PRODUCT_CATEGORIES_SERVICE')

export const PRODUCTS_REPOSITORY = Symbol('PRODUCT_REPOSITORY')
export const PRODUCTS_TRANSLATIONS_REPOSITORY = Symbol('PRODUCT_TRANSLATIONS_REPOSITORY')
export const PRODUCTS_SERVICE = Symbol('PRODUCT_SERVICE')

export const PRODUCTS_VARIANTS_REPOSITORY = Symbol('PRODUCTS_VARIANTS_REPOSITORY')
