export const PASSWORD_HASH_SALT = Symbol('PASSWORD_HASH_SALT')

export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY')
export const USERS_SOCIALS_REPOSITORY = Symbol('USERS_SOCIALS_REPOSITORY')

export const USERS_SERVICE = Symbol('USERS_SERVICE')
export const USERS_REFERRAL_SERVICE = Symbol('USERS_REFERRAL_SERVICE')

export const USERS_REFERRAL_REPOSITORY = Symbol('USERS_REFERRAL_REPOSITORY')
export const USERS_BONUSES_HISTORY_RECORDS_REPOSITORY = Symbol(
	'USERS_BONUSES_HISTORY_RECORDS_REPOSITORY',
)
