export const ORDERS_REPOSITORY = Symbol('ORDERS_REPOSITORY')
export const ORDERS_USERS_REPOSITORY = Symbol('ORDERS_USERS_REPOSITORY')
export const ORDERS_SHIPPINGS_REPOSITORY = Symbol('ORDERS_SHIPPINGS_REPOSITORY')
export const ORDERS_PRODUCTS_REPOSITORY = Symbol('ORDERS_PRODUCTS_REPOSITORY')

export const ORDERS_SERVICE = Symbol('ORDERS_SERVICE')

export const BUCKET_SERVICE = Symbol('BUCKET_SERVICE')
