export const POSTS_REPOSITORY = Symbol('POSTS_REPOSITORY')

export const POSTS_SERVICE = Symbol('POSTS_SERVICE')

export const POSTS_CATEGORIES_REPOSITORY = Symbol('POSTS_CATEGORIES_REPOSITORY')

export const POSTS_CATEGORIES_SERVICE = Symbol('POSTS_CATEGORIES_SERVICE')

export const POST_TYPE_REPOSITORY = Symbol('POST_TYPE_REPOSITORY')

export const POSTS_TYPE_SERVICE = Symbol('POSTS_TYPE_SERVICE')

export const POST_TO_CATEGORY_REPOSITORY = Symbol('POST_TO_CATEGORY_REPOSITORY')

export const POSTS_TRANSLATE_REPOSITORY = Symbol('POSTS_TRANSLATE_REPOSITORY')
export const POSTS_CATEGORIES_TRANSLATE_REPOSITORY = Symbol('POSTS_CATEGORIES_TRANSLATE_REPOSITORY')
export const POSTS_TYPE_TRANSLATE_REPOSITORY = Symbol('POSTS_TYPE_TRANSLATE_REPOSITORY')


