export const SHIPPING_REPOSITORY = Symbol('SHIPPING_REPOSITORY')
export const SHIPPING_NOVA_POSHTA_REPOSITORY = Symbol('SHIPPING_NOVA_POSHTA_REPOSITORY')
export const SHIPPING_SERVICE = Symbol('SHIPPING_SERVICE')

export const SHIPPING_URK_POSHTA_REPOSITORY = Symbol('SHIPPING_UKR_POSHTA_REPOSITORY')
