export const MENU_REPOSITORY = Symbol('MENU_REPOSITORY')
export const MENU_ITEM_REPOSITORY = Symbol('MENU_ITEM_REPOSITORY')
export const MENU_ITEM_TRANSLATE_REPOSITORY = Symbol('MENU_ITEM_TRANSLATE_REPOSITORY')

export const MENU_SERVICE = Symbol('MENU_SERVICE')
export const MENU_ITEMS_SERVICE = Symbol('MENU_ITEMS_SERVICE')
